.PHONY: clean All

All:
	@echo "----------Building project:[ XDibuixos - Debug ]----------"
	@cd "XDibuixos" && "$(MAKE)" -f  "XDibuixos.mk"
clean:
	@echo "----------Cleaning project:[ XDibuixos - Debug ]----------"
	@cd "XDibuixos" && "$(MAKE)" -f  "XDibuixos.mk" clean
