.PHONY: clean All

All:
	@echo "----------Building project:[ Dibuixos - Debug ]----------"
	@"$(MAKE)" -f  "Dibuixos.mk"
clean:
	@echo "----------Cleaning project:[ Dibuixos - Debug ]----------"
	@"$(MAKE)" -f  "Dibuixos.mk" clean
